version: "3.7"

services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    depends_on:
      - phpfpm
    ports:
    - 8081:80
    networks:
      - internal
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  phpfpm:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: on-failure
    networks:
      - internal
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www/html

networks:
  internal:
    external: false
